## Student Attendance Analytics with Pandas

In [2]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [4]:
df = pd.read_excel("aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [5]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""

print("First 10 rows:")
display(df.head(10))

print("DataFrame Shape:")
print(df.shape)

print("Data Types:")
print(df.dtypes)

First 10 rows:

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1

DataFrame Shape:
(59, 12)
Data Types:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [6]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count."""

# Treat the text "Never" as a missing value for the date column
df["Last Present Date"] = df["Last Present Date"].replace("Never", np.nan)

print("Missing values in each column:")
print(df.isnull().sum())

print("\nColumns containing missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

Missing values in each column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       2
Consecutive Absences    0
dtype: int64

Columns containing missing values:
Last Present Date    2
dtype: int64

In [7]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""

df.rename(columns={
    "Roll No": "roll_no",
    "Student Name": "student_name",
    "Subject": "subject",
    "Total Classes": "total_classes",
    "Present": "present",
    "Absent": "absent",
    "Excused": "excused",
    "Attendance %": "attendance_pct",
    "Status": "status",
    "Classes Needed (75%)": "classes_needed_75",
    "Last Present Date": "last_present_date",
    "Consecutive Absences": "consecutive_absences"
}, inplace=True)

print("Updated column names:")
print(df.columns.tolist())

Updated column names:
['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']

In [8]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""

df["attendance_pct"] = (
    df["attendance_pct"].astype(str).str.replace("%", "", regex=False).str.strip()
)
df["attendance_pct"] = pd.to_numeric(df["attendance_pct"], errors="coerce") / 100

df["last_present_date"] = pd.to_datetime(df["last_present_date"], errors="coerce")

print(df[["attendance_pct", "last_present_date"]].head())
print("\nUpdated data types:")
print(df[["attendance_pct", "last_present_date"]].dtypes)

   attendance_pct last_present_date
0            0.67        2026-10-09
1            0.67        2026-10-09
2            0.08        2026-09-22
3            0.92        2026-10-10
4            0.83        2026-10-09

Updated data types:
attendance_pct              float64
last_present_date    datetime64[us]
dtype: object

#### Section 2: Filtering & Selection

In [9]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""

critical_students = df[df["status"].str.strip().str.lower() == "critical"]
critical_students = critical_students.sort_values("attendance_pct", ascending=True)
display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.00,Critical,36 more,NaT,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.00,Critical,36 more,NaT,12
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,0.08,Critical,32 more,2026-09-22,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,0.08,Critical,32 more,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,0.08,Critical,32 more,2026-09-08,9
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,0.17,Critical,28 more,2026-10-06,2
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,0.17,Critical,28 more,2026-09-08,9
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,0.17,Critical,28 more,2026-10-06,2
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-09-22,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-09-29,3
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-10-06,2
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,0.33,Critical,20 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,0.33,Critical,20 more,2026-10-06,2
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,0.42,Critical,16 more,2026-10-06,2
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,0.50,Critical,12 more,2026-10-09,1
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,0.50,Critical,12 more,2026-10-06,2
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,0.58,Critical,8 more,2026-09-25,4
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,0.67,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,0.67,Critical,4 more,2026-10-09,1
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,0.67,Critical,4 more,2026-10-10,0

In [10]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""

fully_absent = df[df["present"] == 0][
    ["roll_no", "student_name", "consecutive_absences"]
]
display(fully_absent)

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [11]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """

print("(a) Safe students using .loc:")
display(df.loc[df["status"].str.strip().str.lower() == "safe"])

print("(b) First 15 rows and columns 2-6 using .iloc:")
display(df.iloc[:15, 1:6])

(a) Safe students using .loc:

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,1.00,Safe,✓ Met,2026-10-10,0
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,1
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-09,1
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,1.00,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0

(b) First 15 rows and columns 2-6 using .iloc:

,student_name,subject,total_classes,present,absent
0,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4
1,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4
2,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11
3,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1
4,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
5,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2
6,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
7,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0
8,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
9,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3
10,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3
11,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3
12,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6
13,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3
14,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1

In [12]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""

students_absent_5_or_more = df.loc[
    df["consecutive_absences"] >= 5,
    ["student_name", "status", "last_present_date"]
]
display(students_absent_5_or_more)

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [13]:
"""Q9. Group the data by Status and compute:
a) Count of students
b) Average attendance %
c) Maximum consecutive absences"""

status_summary = df.groupby("status").agg(
    student_count=("roll_no", "count"),
    average_attendance_pct=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)
display(status_summary)

          student_count  average_attendance_pct  max_consecutive_absences
status
Critical             23                0.300870                        12
Safe                 13                0.932308                         1
Warning              23                0.805652                         2

In [14]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""

df["attendance_category"] = np.select(
    [
        df["attendance_pct"] >= 0.90,
        df["attendance_pct"] >= 0.75,
        df["attendance_pct"] >= 0.60
    ],
    ["Excellent", "Good", "Average"],
    default="Poor"
)

print("Student count in each attendance category:")
display(df.groupby("attendance_category").size().to_frame("student_count"))

Student count in each attendance category:

                     student_count
attendance_category
Average                          3
Excellent                       13
Good                            23
Poor                            20

In [15]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""

totals = df.agg({
    "total_classes": "sum",
    "present": "sum",
    "absent": "sum"
})
print(totals)

total_classes    708
present          451
absent           257
dtype: int64

In [16]:
"""Q12. Group by Status and use .agg() to find:
a) min, max, and mean of Present
b) sum of Absent"""

status_attendance = df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    absent_sum=("absent", "sum")
)
display(status_attendance)

          present_min  present_max  present_mean  absent_sum
status
Critical            0            8      3.608696         193
Safe               11           12     11.153846          11
Warning             9           10      9.695652          53

### Section 4: Feature Engineering & Transformation

In [17]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""

df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)
top_10_risk = df.sort_values("risk_score", ascending=False).head(10)
display(top_10_risk[["roll_no", "student_name", "absent", "consecutive_absences", "risk_score"]])

,roll_no,student_name,absent,consecutive_absences,risk_score
33,4MW24AI036,RAJU ASHOKA RATHOD,12,12,12.0
32,4MW24AI035,RAJATH K K,12,12,12.0
58,4MW25AI401,Omkar Rane,11,9,9.8
41,4MW24AI045,SHRAVYA,10,9,9.4
2,4MW24AI003,ADITYA,11,5,7.4
25,4MW24AI028,MOURYA RAJ H N,9,5,6.6
35,4MW24AI038,RASHMI,11,2,5.6
18,4MW24AI021,KISHAN J,9,3,5.4
22,4MW24AI025,MANMITHA,10,2,5.2
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),10,2,5.2

In [18]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""

df["classes_needed_numeric"] = (
    df["classes_needed_75"].astype(str).str.extract(r"(\d+)")[0].fillna("0").astype(int)
)
display(df[["classes_needed_75", "classes_needed_numeric"]].head(10))

  classes_needed_75  classes_needed_numeric
0            4 more                       4
1            4 more                       4
2           32 more                      32
3             ✓ Met                       0
4             ✓ Met                       0
5             ✓ Met                       0
6             ✓ Met                       0
7             ✓ Met                       0
8             ✓ Met                       0
9             ✓ Met                       0

In [19]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a) "Defaulter" if attendance < 75%
b) "Safe" otherwise """

df["attendance_flag"] = df["attendance_pct"].apply(
    lambda attendance: "Defaulter" if attendance < 0.75 else "Safe"
)
display(df[["student_name", "attendance_pct", "attendance_flag"]].head(10))

              student_name  attendance_pct attendance_flag
0                 ABHIJITH            0.67       Defaulter
1       ABHISHEK KRISHNA P            0.67       Defaulter
2                   ADITYA            0.08       Defaulter
3        AKSHATA JAKAREDDY            0.92            Safe
4                   ANANYA            0.83            Safe
5              ANANYASHREE            0.83            Safe
6    ANKITA TARANATH MESTA            0.83            Safe
7        ANVITH S SHERIGAR            1.00            Safe
8                  APEKSHA            0.83            Safe
9  ARLENE VELORA FERNANDES            0.75            Safe

In [20]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""

df["attendance_range"] = pd.cut(
    df["attendance_pct"] * 100,
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"],
    include_lowest=True,
    
    right=True
)
display(df[["student_name", "attendance_pct", "attendance_range"]].head(10))

              student_name  attendance_pct attendance_range
0                 ABHIJITH            0.67          Warning
1       ABHISHEK KRISHNA P            0.67          Warning
2                   ADITYA            0.08         Critical
3        AKSHATA JAKAREDDY            0.92        Excellent
4                   ANANYA            0.83             Good
5              ANANYASHREE            0.83             Good
6    ANKITA TARANATH MESTA            0.83             Good
7        ANVITH S SHERIGAR            1.00        Excellent
8                  APEKSHA            0.83             Good
9  ARLENE VELORA FERNANDES            0.75          Warning

### Section 5: Advanced Analysis

In [21]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""

attendance_pivot = pd.pivot_table(
    df,
    index="status",
    columns="attendance_category",
    values="roll_no",
    aggfunc="count",
    fill_value=0
)
display(attendance_pivot)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    20
Safe                       0         13     0     0
Warning                    0          0    23     0

In [ ]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""


df["base_name"] = (
    df["student_name"].astype(str).str.strip().str.replace(r"\s*\(.*\)$", "", regex=True)
    .str.split().str[0].str.upper()
)
repeated_base_names = df[df.duplicated("base_name", keep=False)].sort_values("base_name")
display(repeated_base_names)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,0.25,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,RAJATH
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.00,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,Critical,RAJATH
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,0.17,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,SINCHANA
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,SINCHANA

In [23]:
"""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the result."""

# Hypothetical details: update Branch/Semester values if your actual details are different.
Student_Details = pd.DataFrame({
    "roll_no": df["roll_no"],
    "branch": ["AI&ML"] * len(df),
    "semester": [5] * len(df)
})

merged_df = pd.merge(df, Student_Details, on="roll_no", how="inner")
display(merged_df.head(10))

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,branch,semester
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,0.67,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHIJITH,AI&ML,5
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,0.67,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHISHEK,AI&ML,5
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,0.08,Critical,32 more,2026-09-22,5,Poor,7.4,32,Defaulter,Critical,ADITYA,AI&ML,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,0.92,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,AKSHATA,AI&ML,5
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANANYA,AI&ML,5
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANANYASHREE,AI&ML,5
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANKITA,AI&ML,5
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,1.00,Safe,✓ Met,2026-10-10,0,Excellent,0.0,0,Safe,Excellent,ANVITH,AI&ML,5
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,0.83,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,APEKSHA,AI&ML,5
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,0.75,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,ARLENE,AI&ML,5

In [25]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""


critical_students = df[df["status"].str.strip().str.lower() == "critical"]
critical_students.to_csv("critical_students.csv", index=False)



summary_by_status = df.groupby("status").agg(
    student_count=("roll_no", "count"),
    average_attendance_pct=("attendance_pct", "mean"),
    total_present=("present", "sum"),
    total_absent=("absent", "sum"),
    max_consecutive_absences=("consecutive_absences", "max")
)
summary_by_status.to_csv("summary_by_status.csv")


top_10_risk = df.sort_values("risk_score", ascending=False).head(10)
top_10_risk.to_csv("top_10_risk_score.csv", index=False)

print("Exported: critical_students.csv, summary_by_status.csv, top_10_risk_score.csv")

Exported: critical_students.csv, summary_by_status.csv, top_10_risk_score.csv